<a href="https://colab.research.google.com/github/itsdivya1309/Maths-for-ML/blob/main/LinearAlgebra/Basics_of_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Vectors

The set Rn is the set of all n-tuples of real numbers. In set notation this is

`Rn={(x1,x2,x3,⋯,xn):x1,x2,x3,⋯,xn∈R}`

For example, the set R3
represents the set of real triples, (x,y,z)coordinates, in three-dimensional space.

A vector in Rn is an n-tuple, or point, in Rn.

In [2]:
import numpy as np

row_vector = np.array([[1,-4,3,19]])
col_vector = np.array([[1],
                       [-2],
                       [13],
                        [0]])
print('Shape of row vector: ',row_vector.shape)
print('Shape of column vector: ',col_vector.shape)

Shape of row vector:  (1, 4)
Shape of column vector:  (4, 1)


In [3]:
row_vector

array([[ 1, -4,  3, 19]])

In [4]:
col_vector

array([[ 1],
       [-2],
       [13],
       [ 0]])

In [5]:
vec = np.array([1,2,3,0])
vec.shape

(4,)

In [6]:
vec

array([1, 2, 3, 0])

### Vector norm

The norm of a vector is a measure of its length.

* The **L1 norm** is calculated as the
sum of the absolute values of the vector.

This length is sometimes called the taxicab norm or the **Manhattan norm**.

```
L1(v) = ||v||1 = |a1| + |a2| + |a3|
```


* The **L2 norm** is calculated as the square root of the sum of the squared vector values.

It is also known as the **Euclidean norm** as it is calculated as the Euclidean distance from the origin.

```
l2(v) = ||v||2 = sqrt(a1^2 + a2^2 + a3^2)
```


* The **max norm** that is calculated as the maximum vector values.

It is also called infinity norm.

```
maxnorm(v) = ||v||inf = max(|a1|, |a2|, |a3|)
```



In [8]:
from numpy.linalg import norm

new_vector = row_vector.T
print("Transpose of row vector: \n", new_vector)

norm1 = norm(new_vector,1)
norm2 = norm(new_vector,2)
max_norm = norm(new_vector, np.inf)

print('L1 norm is: %.1f'%norm1)
print('L2 norm is: %.1f'%norm2)
print('L_inf norm is: %.1f'%max_norm)

Transpose of row vector: 
 [[ 1]
 [-4]
 [ 3]
 [19]]
L1 norm is: 27.0
L2 norm is: 19.7
L_inf norm is: 19.0


### Dot product


The dot product of two vectors is the sum of the product of the respective elements in each vector and is denoted by ⋅, and v⋅w
```
v⋅w=∥v∥2∥w∥2cosθ
```

In [11]:
"""
Compute the angle between the vectors v=[10,9,3] and w=[2,5,12].
"""
#from numpy import arccos, dot

v = np.array([[10,9,3]])
w = np.array([[2,5,12]])
theta = np.arccos(np.dot(v,w.T)/(norm(v)*norm(w)))

print(theta)

[[0.97992471]]


### Cross product

the cross product between two vectors, v
 and w
, is written v×w
. It is defined by

```
v×w=∥v∥2∥w∥2sin(θ)n
```

where θ is the angle between the v and w (which can be computed from the dot product) and n is a vector perpendicular to both v and w with unit length (i.e., the length is one).

In [10]:
"""
Given the vectors v=[0,2,0] and w=[3,0,0], use the Numpy function cross
to compute the cross product of v and w.
"""
v = np.array([[0,2,0]])
w = np.array([[3,0,0]])
print(np.cross(v,w))

[[ 0  0 -6]]


### Linear independance

A set is called linearly independent if no object in the set can be written as a linear combination of the other objects in the set. A set of vectors that is not linearly independent is linearly dependent.

In [12]:
"""
Given the row vectors v=[0,3,2], w=[4,1,1], and u=[0,−2,0],
write the vector x=[−8,−1,4] as a linear combination of v, w, and u.
"""

v = np.array([[0,3,2]])
w = np.array([[4,1,1]])
u = np.array([[0,-2,0]])

x = 3*v -2*w + 4*u

print(x)

[[-8 -1  4]]


## Matrices

In [14]:
"""
Let the Python matrices P=[[1,7],[2,3],[5,0]] and Q=[[2,6,3,1],[1,2,3,4]].
Compute the matrix product of P and Q. Show that the product of Q and P
will produce an error.
"""
P = np.array([[1,7],[2,3],[5,0]])
Q = np.array([[2,6,3,1],[1,2,3,4]])
print('P: \n',P)
print('Q: \n',Q)
print('P.Q \n',np.dot(P,Q))
print(np.dot(Q,P))

P: 
 [[1 7]
 [2 3]
 [5 0]]
Q: 
 [[2 6 3 1]
 [1 2 3 4]]
P.Q 
 [[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


ValueError: ignored

In [18]:
"""
Use Python to find the determinant of the matrix
M=[[0,2,1,3],[3,2,8,1],[1,0,0,3],[0,3,2,1]].
Use the np.eye function to produce a 4×4 identity matrix, I.
Multiply M by I to show that the result is M.
"""
from numpy.linalg import det

M = np.array([[0,2,1,3],
              [3,2,8,1],
              [1,0,0,3],
              [0,3,2,1]])
print('M: \n',M)
print('Determinant: %.1f'%det(M))
I = np.eye(4)
print('4X4 I: \n',I)
print('MXI: \n',np.dot(M,I))

M: 
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
4X4 I: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
MXI: 
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


In [19]:
"""
The matrix M (in the previous example) has a nonzero determinant.
Compute the inverse of M. Show that the matrix P=[[0,1,0],[0,0,0],[1,0,1]]
has a determinant value of 0 and therefore has no inverse.
"""
from numpy.linalg import inv
print("Inv M:\n", inv(M))
P = np.array([[0,1,0],
              [0,0,0],
              [1,0,1]])
print('det(P):\n',det(P))

Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
det(P):
 0.0


### Condition number & Rank of matrix

* A matrix that is close to being singular (i.e., the determinant is close to 0) is called ill-conditioned.
* The condition number is a measure of how ill-conditioned a matrix is, and it can be computed using Numpy’s function cond from linalg. The higher the condition number, the closer the matrix is to being singular.
* The rank. of an m×n matrix A is the number of linearly independent columns or rows of A, and is denoted by rank(A).
* A matrix is called full rank. if rank (A)=min(m,n).

In [21]:
"""
Matrix A=[[1,1,0],[0,1,0],[1,0,1]], compute the condition number and rank
for this matrix. If y=[[1],[2],[1]], get the augmented matrix [A, y].
"""
from numpy.linalg import cond, matrix_rank

A = np.array([[1,1,0],[0,1,0],[1,0,1]])
y = np.array([[1],[2],[1]])

print('Condition number:\n',cond(A))
print('Rank of A:\n',matrix_rank(A))
A_y = np.concatenate((A,y), axis = 1)
print('Augmented matrix:\n',A_y)

Condition number:
 4.048917339522305
Rank of A:
 3
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]
